# Generated by Django 2.2.5 on 2019-11-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allfreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, null=True)),
                ('freqcet4', models.IntegerField(blank=True, null=True)),
                ('freqcet6', models.IntegerField(blank=True, null=True)),
                ('freqz4', models.IntegerField(blank=True, null=True)),
                ('freqz8', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'allFreq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, null=True)),
                ('trans', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'four',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, null=True)),
                ('trans', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proeight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, null=True)),
                ('trans', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Six',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, null=True)),
                ('trans', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'six',
                'managed': False,
            },
        ),
    ]
